### ISSUE TITLE
Sound is playing but without picture 

### ISSUE THREAD

**Issue by TomTomB** [ZeBobo5/Vlc.DotNet#328] opened 2017-10-07 17:14 UTC
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : Newest
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x86/x64 latest 3.0.0 + current stable 2.2.6 from offical ftp server 
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows x86/x64

# Summary

I am using the sample code from the wiki for a WPF app.
For testing things, I created a new project for the VLC player. In there everything works perfectly fine. 
So I moved the code to my current project. Curiously when I start the app only the sound of the video gets played. The actual vlc element stays blank. 
So I added the debugging options from the wiki to the vlc instance. 
The console output looks like that:
https://www.pic-upload.de/view-34050135/vlc_output.png.html
   

Any advice?
Thanks...

EDIT: 
Well I´ve found the problem. 
It seems like the WPF VlcControl does not like the `AllowsTransparency="True"` property. After removing it from my window everything works fine. 

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment] 2017-10-09 07:21
`AllowsTransparency`? Then it's a duplicate of #21 . Thanks for your bugreport, but I have to close this.

**Closed by jeremyVignelles** 2017-10-09 07:21 UTC
