### ISSUE TITLE
Volume is not being reset before calling play.

### ISSUE THREAD

**Issue by alexhuang92** [ZeBobo5/Vlc.DotNet#381] opened 2018-02-12 20:08 UTC
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : Core
- **libvlc version** : (2.2.8/2.2.5.1/3.0.0) (x86) http://download.videolan.org/pub/videolan/vlc/2.2.8/
- **.net version** : .NET 4.5.1
- **Project language** : (C#)
- **Project build architecture** : (x86)
- **Operating system** : Windows 10 Pro

# Summary
My application simulates fading in/out by incrementing/decrementing volumes through timer-based events. During the first playthrough volumes are correctly set and correctly increment to simulate a fade-in effect but when I transition to another media item, the volumes do not reset and instead keep getting larger.

I instantiate two VlcMediaPlayer objects which take turns on their roles for fading in and fading out. 

Player1 fades in, increments the volume, fades out. While Player1 fades out, Player2 fades in, increments its volume and then fades out. At this point Player1 needs to fade back in with a starting volume of zero but instead jumps an undeterminate amount. In the code samples below, the reference to `this.MainPlayer` therefore references either Player1 or Player2 depending on whos turn it is to fade in.

During the first playthrough, the volumes correctly get set from 0 to 40.
During the second playthrough, volumes go from 28 to 66.
During the third playthrough, volumes go from 67 to 130.

I've attempted to set the volume inside a Task.Run() 
     `Task.Run(() =>this.MainPlayer.Player.Audio.Volume = volume);`
which does not seem to have an effect as well as trying libvlc versions 2.2.8/2.2.5.1/3.0.0.
I always tried setting the initial starting volume in various VlcMediaPlayer events: 
Opening, MediaChanged. 

When a player is nearing the end of its media's duration, I also fade out the volume to zero before I set and queue up my next media item.

`       
       
    private void SetAndPlayOnMainPlayer(Media trackToPlay)
        {
                var volume = 0;

                    this.MainPlayer.Player.Audio.Volume = volume;
                    this.MainPlayer.Player.SetMedia(new FileInfo(trackToPlay.FilePath), new string[] { });
                    System.Threading.Tasks.Task.Run(() => this.MainPlayer.Player.Play());
        }
        // event handler for timer's elapsed event
        private void FadeInTimer_Elapsed(object sender, ElapsedEventArgs e)
        {
                    this.MainPlayer.Player.Audio.Volume += (int)(FadeInVolumeAdjustmentPerTick);
         }
`

(What happens, when, how? Steps to reproduce (with sample codes))

- [ X] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment] 2018-02-12 20:23
Probable duplicate of #130

**Comment by LifeguardConcepts** [comment] 2018-02-13 07:12
Jeremy,
Thanks for acknowledging this issue.  Any suggestions on a work around or final solution? Do we know the root of the issue?  I know the duplicate issue is 2 years old so it would be great to either have a work around or given our situation move on from Vlc.

**Comment by jeremyVignelles** [comment] 2018-02-13 22:04
Hi, I'm sorry, I could not reproduce the issue with vlc-3.0.0 x64 just downloaded.

Here is what I did:
- Take the Sample.Wpf.Minimal project
- Open the MainWindow.xaml.cs file
- Replace the playing code with the following:
- Disabled "prefer 32 bits in project properties"
- Pasted vlc-3.0.0-win64.zip in Vlc.DotNet/lib/x64 folder
- Pressed Debug

```
            this.VlcControl.SourceProvider.CreatePlayer(libDirectory/* pass your player parameters here */);
            Console.WriteLine(this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume);
            this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume = 50;
            Console.WriteLine(this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume);
            this.VlcControl.SourceProvider.MediaPlayer.SetMedia(new Uri(
                "http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi"));
            this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume = 55;
            Console.WriteLine(this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume);
            this.VlcControl.SourceProvider.MediaPlayer.Play();
            this.VlcControl.SourceProvider.MediaPlayer.Playing += (s, e) =>
            {
                Console.WriteLine("Playing");
                Console.WriteLine(this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume);
                this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume = 60;
                Console.WriteLine(this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume);
            };

            Task.Run(async () =>
            {
                await Task.Delay(TimeSpan.FromSeconds(2));
                this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume = 65;
                Console.WriteLine(this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume);
                await Task.Delay(TimeSpan.FromSeconds(5));
                Console.WriteLine(this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume);
                this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume = 70;
                Console.WriteLine(this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume);
                this.VlcControl.SourceProvider.MediaPlayer.Play(new Uri(
                    "http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_surround-fix.avi"));
                this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume = 75;
                Console.WriteLine(this.VlcControl.SourceProvider.MediaPlayer.Audio.Volume);
            });
```

The output is:
```
100
50
55
Playing
55
60
65
65
70
75
Playing
75
60
```

Could you tell me what I need to change in order to reproduce your issue?

**Comment by LifeguardConcepts** [comment] 2018-02-14 02:31
This looks awfully close and the issue is pretty old

https://trac.videolan.org/vlc/ticket/14963

**Comment by jeremyVignelles** [comment] 2019-07-15 20:24
Hi,
Did you find any solution since then ?

I'd personnally try something like `--aout=directsound`. I've had several issues with the default `mmdevice` audio plugin. See #524 .

Feel free to reopen if you still need help

**Closed by jeremyVignelles** 2019-07-15 20:24 UTC
