### ISSUE TITLE
Control freezes while recording with webcam and unplug the selected device

### ISSUE THREAD

**Issue by saiprasadb** [ZeBobo5/Vlc.DotNet#359] opened 2017-12-12 11:38 UTC
I am using vlc.dotnet from nuget packages, with windows forms and am recording the video using webcam to server using rtmp,
if I select the **same device for video and audio** and after few minutes **I have unplugged the webcam and trying to stop the recording at this moment vlcControl.Stop() freezes**, below is the code

string vlcDirectoryPath = Application.ExecutablePath.Substring(0, Application.ExecutablePath.LastIndexOf(@"\")) + @"\vlc";
            previewControl = new VlcControl();
            previewControl.EncounteredError += PreviewControl_EncounteredError;
            previewControl.Paused += PreviewControl_Paused;
            previewControl.Stopped += PreviewControl_Stopped;
            previewControl.VlcLibDirectory = new DirectoryInfo(vlcDirectoryPath);
            previewControl.EndInit();
            previewPanel.Controls.Add(previewControl);
            previewControl.BackColor = System.Drawing.Color.Black;
            previewControl.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            previewControl.Location = new System.Drawing.Point(0, 0);
            previewControl.Name = "Preview";
            previewControl.Rate = 0.0F;
            previewControl.Size = new System.Drawing.Size(280, 250);

            string[] streamingaArguments = new string[]
                {
                    ":dshow-vdev=**Face2Face ROBO K20 Webcam**",
                    ":dshow-size=640*480", // Webcam supportted resolution.
                    ":dshow-adev= ",
                    ":live-caching=10",
                    ":dshow-adev=**Microphone (Face2Face ROBO K20 Webcam)**",
                    
                    "sout=#duplicate{dst=display," +
                    "dst=transcode{vcodec=h264,scale=Auto,width=480,height=360,vb=300,acodec=libvo_aacenc,ab=48,samplerate=22050,channels=2,deinterlace}}" +
                    ":std{access=rtmp,mux=ffmpeg{mux=flv}," +                   
                    "dst=rtmp://abc.com/xyz/LiveStream1}" 

                    
                };
            previewControl.Play(@"dshow://", streamingaArguments);

After few minutes I have unplugged the webcam and to start the recording I have written previewControl.Stop() which gets fails and makes a deadlock situation , even tried with Dispose too.

Please help me to resolve this issue.

**Comment by jeremyVignelles** [comment] 2017-12-13 08:24
`Stop` and `Dispose` must be called from the same thread that created the control. If you are using WPF, this is probably the Dispatcher thread.

If you are calling `Stop()` from inside a callback, you are probably doing it wrong.

try with:
```
Dispatcher.BeginInvoke(() => {
   // Your code here
});
```

**Comment by saiprasadb** [comment] 2017-12-13 10:19
Hi JeremyVignelles,

I have tried as per your suggestion in both winforms and wpf too but no luck, again I have endedup with the same deadlock.
**Here is the log of the vlc control when I unplug the webcam while recording video to server using rtmp
**
libVlc : Warning Reseting video sync @ stream_out_transcode
libVlc : Warning late buffer for mux input (1993498) @ core
libVlc : Error ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 110 ms) @ core
libVlc : Error ES_OUT_RESET_PCR called @ core
libVlc : Warning invalid frame size (zu < zu) @ rawvideo
libVlc : Debug auto hiding mouse cursor @ core


**Below is the entire WPF code**
public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Start_Click(object sender, RoutedEventArgs e)
        {
            string vlcDirectoryPath = System.Reflection.Assembly.GetExecutingAssembly().Location.ToString();

            vlcDirectoryPath = vlcDirectoryPath.Substring(0, vlcDirectoryPath.LastIndexOf(@"\")) + @"\vlc";
            this.previewControl.MediaPlayer.VlcLibDirectory = new DirectoryInfo(vlcDirectoryPath);            

            this.previewControl.MediaPlayer.Log += (vlcsender, args) =>
            {                
                System.Diagnostics.Debug.WriteLine(string.Format("libVlc : {0} {1} @ {2}", args.Level, args.Message, args.Module));
            };

            var options = new string[]
            {
                
            };

            this.previewControl.MediaPlayer.VlcMediaplayerOptions = options;
            
            this.previewControl.MediaPlayer.EndInit();

            string[] streamingaArguments = new string[]
                    {
                    ":dshow-vdev=Face2Face ROBO K20 Webcam",
                    ":dshow-size=640*480", // Webcam supportted resolution.
                    ":dshow-adev= ",
                    ":live-caching=10",
                    ":dshow-adev=Microphone (Face2Face ROBO K20 Webcam)",
                    "sout=#duplicate{dst=display," +
                    "dst=transcode{vcodec=h264,scale=Auto,width=480,height=360,vb=300,acodec=libvo_aacenc,ab=48,samplerate=22050,channels=2,deinterlace}}" +
                    ":std{access=rtmp,mux=ffmpeg{mux=flv}," +
                    "dst=rtmp://abc.com/VidDev/LiveStream}"
                    };

            this.previewControl.MediaPlayer.Play(@"dshow://", streamingaArguments);
        }

        private void Stop_Click(object sender, RoutedEventArgs e)
        {
            Dispatcher.BeginInvoke(new Action(() => { this.previewControl.MediaPlayer.Stop();this.previewControl.MediaPlayer.Dispose(); }));            
        }
    }

Please help me to resolve the issue.

**Comment by jeremyVignelles** [comment] 2017-12-13 13:03
You didn't fill the issue template, and I need more info : Which version of libvlc are you using? Could you try with at least with the last 3.0.0-rc1 nighly?

**Comment by saiprasadb** [comment] 2017-12-14 04:05
Hi JermyVignelles,

Apologize for not providing the required info, below are the details
libvlc : 2.2.0.0
libvlccore : 2.2.0.0
vlc.DotNet : 2.2.1.0

As per you suggestion in the above comment I will try with the latest libvlc.
I tried with the Stop() or Dispose() separately but it does not worked out in my case.

**Comment by saiprasadb** [comment] 2018-01-08 05:06
Hi JermyVignelles,

Any updates on the above issue, still I didnt find the solution for this.

Please help me to resolve this issue.

**Comment by jeremyVignelles** [comment] 2018-01-08 06:15
Did you try with vlc release candidate as you said you would do? I suspect the issue is with the dshow plugin in libvlc, because I don't see what's wrong with your code

**Comment by jeremyVignelles** [comment] 2018-02-15 23:37
Also, did you try with VLC itself? does it crash the same way? VLC 3.0.0 is out now, and it might worth the try.

**Comment by jeremyVignelles** [comment] 2018-12-06 22:40
Closing since no answer for a long time. Reopen if needed.

**Closed by jeremyVignelles** 2018-12-06 22:40 UTC
