### ISSUE TITLE
Problem in set time or position

### ISSUE THREAD

**Issue by kapitaneo** [ZeBobo5/Vlc.DotNet#295] opened 2017-09-11 14:45 UTC
Hello everybody. When i set time or position, video time changed but then time add small value (example +190), different video -different value. And TimeChanged not calls on this change value. What is it? May be someone see this problem? May be it's problem in libriary?

Thanks

**Comment by kapitaneo** [comment] 2017-09-12 08:09
This problem i saw in example for vlc.dotnet too. If we add small value to time example i need 1-25 milsec 1 frame in video or other.

**Comment by jeremyVignelles** [comment] 2017-09-12 09:07
That would be great if you shared a sample code so that I can have a look at it

**Comment by kapitaneo** [comment] 2017-09-12 13:02
Thanks for help i add screenshots in order
![screenshot_9](https://user-images.githubusercontent.com/21293852/30327132-a3b20f1e-97d3-11e7-9d87-72a4b250fcb0.png)
![screenshot_10](https://user-images.githubusercontent.com/21293852/30327145-b081d2ec-97d3-11e7-849a-293248ed05c2.png)
![screenshot_11](https://user-images.githubusercontent.com/21293852/30327151-b39b33ec-97d3-11e7-8eac-e0352ed8cb8f.png)

**Comment by Mistralys** [comment] 2017-09-27 14:26
I can confirm this. When setting the Time property of the control (when paused), querying the property directly after setting it shows the correct value. However, querying it again a short while later shows a slightly different value. I can only guess what happens in the background.

In my case I largely solved the issue by storing the time value I want to seek to in a separate property, and working exclusively with that - disregarding the value the VLC control's Time property exposes. In essence I only use the VLC control's Time property for writing, not reading. That way the slight discrepancy in time values does not add up over time.

Illustration with my application's logging output:

    Seek forward clicked.
    Last seek position: 426225
    Actual player position: 426249
    Seeking to +100ms: 426325
    Video player | Seeking to milliseconds [426325], [22,17953%]

    Seek forward clicked.
    Last seek position: 426325
    Actual player position: 426332
    Seeking to +100ms: 426425
    Video player | Seeking to milliseconds [426425], [22,18474%]

    Seek forward clicked.
    Last seek position: 426425
    Actual player position: 426425
    Seeking to +100ms: 426525
    Video player | Seeking to milliseconds [426525], [22,18994%]

This shows the discrepancy pretty well between the seek position I want to set (Last seek position) and the value of the VLC control's Time property. It's not much of a difference, but in my case when saving screenshots, users often did not get the exact frame that was shown on screen. It still isn't perfect, but close enough. Only seeking by frames or keyframes could improve it.

**Comment by jeremyVignelles** [comment] 2017-09-27 14:42
Hi, thanks for all your reports.
Unfortunately, I'm a bit busy right now, but if you could send me an example code, that would be really useful to get it fixed.
Also please post:
- The version of vlc.dotnet you are using
- Does this also happen with latest develop version?
- Which version of libvlc are you using?
- With which file can I try it out? maybe one of https://peach.blender.org/download/ ?

Thanks for your help

**Comment by jeremyVignelles** [comment] 2018-12-06 22:43
Closing for now, since it's been a long time, VLC 3.0 is now out, and I suspect it's an issue with the demuxer used, not with VLC.DotNet (did you try with VLC?)

**Closed by jeremyVignelles** 2018-12-06 22:43 UTC
