### ISSUE TITLE
System.OutOfMemoryException at Vlc.DotNet.Wpf.VlcVideoSourceProvider.DisplayVideo(IntPtr, IntPtr)

### ISSUE THREAD

**Issue by LateBeginners** [ZeBobo5/Vlc.DotNet#413] opened 2018-04-25 00:56 UTC
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version (3.0)
- **Vlc.DotNet project used (WPF)
- **libvlc version x86
- **.net version** : (4.5)
- **Project language** : (C#)
- **Project build architecture** : x86
- **Operating system** : (Windows x64)

# Summary

System.OutOfMemoryException
at System.Windows.Threading.DispatcherOperationTaskSource`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Initialize(System.Windows.Threading.DispatcherOperation)
at System.Windows.Threading.Dispatcher.LegacyBeginInvokeImpl(System.Windows.Threading.DispatcherPriority, System.Delegate, System.Object, Int32)
at System.Windows.Threading.Dispatcher.BeginInvoke(System.Delegate, System.Object[])
at Vlc.DotNet.Wpf.VlcVideoSourceProvider.DisplayVideo(IntPtr, IntPtr)

**Comment by jeremyVignelles** [comment] 2018-04-25 06:54
Could you be more explicit? I don't have a crystall ball :crystal_ball:

- What kind of file are you trying to play? Is that a 4k video
- Does that happen only with this video or with any video?
- Does this happen immediately or after some time playing?
- Does it happen only in your app or in the sample as well?
- Does it also happen in x64?
- How much RAM do you have on your computer? how much is free?
- What have you tried to solve the problem by yourself.

By answering those questions, you will increase the likeliness that someone can help you solve your issue.

**Comment by LateBeginners** [comment] 2018-04-25 14:32
The video is rtsp stream with 1920 * 1080.  
The issue occurs when playing some unstable video after some time. 
It's in my app which use VlcControl in WPF 3.0.    
The machine is x64, but the app is build on x86.
RAM is 8GB, many time 4.5G is free.

Thanks

**Comment by LateBeginners** [comment] 2018-04-28 21:53
Can help

**Comment by jeremyVignelles** [comment] 2018-04-28 22:01
You will probably have a lower RAM usage by using the WinForms control.
It's hard to tell if it's a memory leak that causes this, increasing the memory usage until the OOME point is reached, or a normal memory usage that, added to your app usage reaches that point.
Are you able to reproduce this with the Minimal WPF sample from the github repository? which version of libvlc are you using? 3.0.2?

**Comment by dilandau2001** [comment] 2018-10-27 22:02
I think this issue won't happen again with:
#477 and #474 

The other possible reason is that your application is x86 and running consuming close to 850 MB RAM. If you have this problem you could do this:
[Make your x86 application large address aware](https://stackoverflow.com/questions/1346480/how-to-make-a-net-application-large-address-aware)
With this change, a single x86 process could handle theoretically up to 4 GB although in reality around 3GB your application will run pretty slow.

**Comment by jeremyVignelles** [comment] 2018-11-11 20:42
I'm closing this since you didn't answer. Please reopen if you think the issue is still there.

**Closed by jeremyVignelles** 2018-11-11 20:42 UTC
