### ISSUE TITLE
Is there a way to play audio with negative rate (FastRewind)

### ISSUE THREAD

**Issue by QuantumDeveloper** [ZeBobo5/Vlc.DotNet#631] opened 2020-03-23 11:26 UTC
Hi.

I see that rewind can be set to negative values to play stream in backward order.
But setting negative rate is not changing the playback itself.

So, I want to ask is there a way to  do a rewind in VLC?

**Comment by txelu** [comment] 2020-03-23 11:49
Unless the audio streams behave differently than the video streams, I think it is not possible. I tried to do it some time ago with no luck and there is a closed issue regarding this (#549).

**Comment by jeremyVignelles** [comment] 2020-03-23 11:56
Thanks txelu, it's indeed a duplicate of #549 . I don't know if things changed in 4.0, but you should ask VideoLAN developpers directly.

**Closed by jeremyVignelles** 2020-03-23 11:56 UTC
