### ISSUE TITLE
Recording not saving video, only audio (SOMETIMES)

### ISSUE THREAD

**Issue by morl0048** [ZeBobo5/Vlc.DotNet#448] opened 2018-07-20 18:36 UTC
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x86 using this link's instruction -> https://github.com/ZeBobo5/Vlc.DotNet/wiki/Using-Vlc.DotNet-in-WinForms (nuget package manager)
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows10 x64

# Summary

(What happens, when, how? Steps to reproduce (with sample codes))

The c# app i'm developping has multiple vlcControllers on it.
Here's how I start my recordings:
```
/// <summary>
        /// Starts a video recording of the target camera
        /// Returns false if:
        /// 1)There's too many player playing the wanted stream
        /// 2)There's already a file with the same name
        /// 3)There's an unexpected error
        /// </summary>
        /// <param name="indexCam"></param>
        /// <param name="path"></param>
        /// <returns></returns>
        private bool startRecording(int indexCam, string path)
        {
            path += "\\";
            string savePath = string.Format("{0}{1:yyyy_MM_dd_HH-mm-ss}.avi", path, System.DateTime.Now);
            try
            {
                System.IO.Directory.CreateDirectory(path);
                if (File.Exists(savePath))
                {
                    MessageBox.Show("Recording error :\r\nCan't override existing recording.");
                    return m_recordingModeVideoList[indexCam] = false;
                }

                foreach (VlcControl recorder in this.Controls.OfType<VlcControl>())
                {
                    if (Convert.ToInt32(recorder.Tag) == indexCam)
                    {
                        string[] options = { ":sout=#duplicate{dst=std{access=file,mux=" + "avi" + ",dst='" + savePath + "'},dst=display}" };
                        recorder.Play(m_streamList[indexCam].URL, options);

                        while (recorder.State == Vlc.DotNet.Core.Interops.Signatures.MediaStates.NothingSpecial) { }//wait for opening

                        while (recorder.State == Vlc.DotNet.Core.Interops.Signatures.MediaStates.Opening) { }//wait for playing or error

                        if (recorder.State != Vlc.DotNet.Core.Interops.Signatures.MediaStates.Playing)
                        {
                            recorder.Stop();
                            MessageBox.Show("Recording error :\r\nToo many players. Please remove the corrupted file from the video folder.");
                            //delete the corrupted file from the video folder
                            //vvv thinking if it's safe to delete this file without asking first.... uncomment if ok vvv
                            File.Delete(savePath);
                            return m_recordingModeVideoList[indexCam] = false;
                        }
                        break;
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Recording error :\r\n" + ex.Message);
                return m_recordingModeVideoList[indexCam] = false;
            }

            return true;
        }
```
When I want to stop the streaming/recording, I simply use the `vlcRecorder.stop()` method.
The problem isn't constant either.... I don't know what I'm doing wrong!

- [I don't know how to test this with VLC] I confirm that my issue doesn't happen in VLC itself.

**Comment by morl0048** [comment] 2018-07-20 19:03
I found a way to test my issue using VLC and I get the same problem...

I open my camera stream using the open network stream option under the Media tab.
![image](https://user-images.githubusercontent.com/36162651/43020161-28b3f986-8c2d-11e8-9fe6-435319b1009b.png)

When the stream is open, I then use the recording option.
![image](https://user-images.githubusercontent.com/36162651/43020242-59340024-8c2d-11e8-9825-4ed99448f52f.png)

And I press it again when I want the recording to stop.

But, even with VLC, certain files seem to be without image recording...
Some are working as intended:
![image](https://user-images.githubusercontent.com/36162651/43020346-ba629bc6-8c2d-11e8-8856-014e37763816.png)

And some others just don't show the images (but can play audio):
![image](https://user-images.githubusercontent.com/36162651/43020396-e2ded358-8c2d-11e8-8ab4-67ad4e319e47.png)

So, I guess the problem is with VLC itself...

Is there anywhere I could get some information on this issue?

**Comment by jeremyVignelles** [comment] 2018-07-20 19:23
I'm not at home, but rtsp recording is broken in vlc. I already posted an issue on vlc's trac (look for my name there)

**Comment by morl0048** [comment] 2018-07-20 19:44
I don't see your name, but I see a bunch of bugs hahaha
https://trac.videolan.org/vlc/query?status=assigned&status=closed&status=new&status=reopened&summary=~recording&col=id&col=summary&col=status&col=owner&col=priority&col=milestone&col=component&col=version&order=priority
Thanks for the help!

**Comment by jeremyVignelles** [comment] 2018-07-20 19:57
Closing as not a bug in Vlc.DotNet

**Closed by jeremyVignelles** 2018-07-20 19:57 UTC

**Comment by jeremyVignelles** [comment] 2018-07-21 06:53
Here is the link you can track and ask for help : https://trac.videolan.org/vlc/ticket/18940

**Comment by jeremyVignelles** [comment] 2018-07-21 07:00
The only way I found so far is to fix that myself and build my own modified vlc. it's long and painful, but it's the only way I found...

**Comment by morl0048** [comment] 2018-07-23 18:45
I think the problem goes away when using the MP4 muxer....

I changed these lines:
`string savePath = string.Format("{0}{1:yyyy_MM_dd_HH-mm-ss}.mp4", path, System.DateTime.Now);`
`string[] options = { ":sout=#duplicate{dst=std{access=file,mux=" + "mp4" + ",dst='" + savePath + "'},dst=display}" };`

No idea why...
