### ISSUE TITLE
WPF : Play multiple videos simultaneously

### ISSUE THREAD

**Issue by mayurkgithub** [ZeBobo5/Vlc.DotNet#319] opened 2017-09-26 09:23 UTC
I have a question about Vlc.DotNet.Wpf

# Generic information

- **Vlc.DotNet version** : (2.1.154.0)
- **Vlc.DotNet project used** : (WPF)
- **libvlc version** : (2.2.5.1) (x64) + how did you get it? from http://download.videolan.org/pub/videolan/vlc/
- **.net version** : (4.5)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU (prefer 32bits))
- **Operating system** : (Windows 8.1 Enterprise) (x64)

# Summary

Hello,

I could able to implement WPF application to play single video through this tutorial https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started and now my requirement is that I want to add a list of video file path's to a playlist object of MediaPlayer instance and when play() method is called it should play all videos simultaneously with auto repeat option should be configurable to enabled or disabled. I gone through all issues on GitHub and also did R&D yet no luck finding the exact solution. Is it possible in WPF anyway or documentation available for the same?

Appreciate your help and looking forward positive answer. Thanks in advance!

**Comment by jeremyVignelles** [comment] 2017-09-26 09:30
Hi, welcome on github and on this library 😄 
I think that playing videos simultaneously can be made by creating serveral VLC controls (didn't test that). You are still responsible to write the code that plays all the components when you click a button.

As for auto-repeat, please see this issue : https://github.com/ZeBobo5/Vlc.DotNet/issues/96 

Please share your findings 😉

**Comment by mayurkgithub** [comment] 2017-09-27 09:37
Hello,
Kindly review my code below and i am trying to overlap vlc control to play next video when one video is completed playing but no luck. Suggest me possible changes please.

<UserControl
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:ScrollTextAnimation_Sample" x:Class="ScrollTextAnimation_Sample.VLCMediaPlayerSample" 
             mc:Ignorable="d" 
             d:DesignHeight="600" d:DesignWidth="600">
    <Grid Name="grdMain">
        <Vlc:VlcControl xmlns:Vlc="clr-namespace:Vlc.DotNet.Wpf;assembly=Vlc.DotNet.Wpf" x:Name="vlcTest" />
    </Grid>
</UserControl>


    public partial class VLCMediaPlayerSample : UserControl
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VLCMediaPlayerSample"/> class.
        /// </summary>
        public VLCMediaPlayerSample()
        {
            InitializeComponent();
            this.vlcTest.MediaPlayer.EndReached += MediaPlayer_EndReached;
            this.InitVlcControl(this.vlcTest);

            this.vlcTest.MediaPlayer.SetMedia(new Uri(@"file:///D:\Mayur\Clash Royale- FLYING MACHINE (New Clash Royale Card!) - YouTube.mkv").AbsoluteUri);
            this.vlcTest.MediaPlayer.Play();
        }

        /// <summary>
        /// Handles the EndReached event of the MediaPlayer control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="VlcMediaPlayerEndReachedEventArgs"/> instance containing the event data.</param>
        void MediaPlayer_EndReached(object sender, VlcMediaPlayerEndReachedEventArgs e)
        {
            try
            {
                this.vlcTest.MediaPlayer.Stop();

                this.InitVlcControl(this.vlcTest);

                this.vlcTest.MediaPlayer.Play(@"file:///D:\Mayur\Digicor INTEL video - YouTube.mp4");
            }
            catch (Exception ex) { }
        }

        /// <summary>
        /// Plays the single video.
        /// </summary>
        /// <param name="vlcControl">The VLC control parameter.</param>
        private void InitVlcControl(VlcControl vlcControl)
        {
            try
            {
                this.GetVlcControl(ref vlcControl);
            }
            catch (Exception ex)
            {
            }
        }

        /// <summary>
        /// Gets the VLC control.
        /// </summary>
        /// <param name="vlcControl">The VLC control parameter.</param>
        private void GetVlcControl(ref VlcControl vlcControl)
        {
            //VlcControl vlcControl = new VlcControl();

            if (IntPtr.Size == 4)
            {
                // Use 32 bits library
                vlcControl.MediaPlayer.VlcLibDirectory = new DirectoryInfo(System.IO.Path.Combine(Environment.CurrentDirectory, "libvlc_x86"));
            }
            else
            {
                // Use 64 bits library
                vlcControl.MediaPlayer.VlcLibDirectory = new DirectoryInfo(System.IO.Path.Combine(Environment.CurrentDirectory, "libvlc_x64"));
            }

            var options = new string[]
                {
                    // VLC options can be given here. Please refer to the VLC command line documentation.
                };

            vlcControl.MediaPlayer.VlcMediaplayerOptions = options;

            // Load libvlc libraries and initializes stuff. It is important that the options (if you want to pass any) and lib directory are given before calling this method.
            vlcControl.MediaPlayer.EndInit();
        }
    }

**Comment by jeremyVignelles** [comment] 2017-09-27 14:30
Are you looking for the Playlist feature, as in #193 ?

As for suggestions, I'm not sure of anything, but you shouldn't probably call EndInit on the same instance again. Either you can swap  controls entierly, or try to call Play() directly a second time.

**Comment by mayurkgithub** [comment] 2017-09-28 06:01
Hi Jeremy,

Thank you for the response and could you please provide any documentation for playlist feature ??? I could not find my answer straightforward also I tried calling Play and SetMedia methods inside MediaPlayer_EndReached method but there is no error and nothing happens and MediaPlayer.State value showing up Ended state. What are the basic steps to prepare a playlist i need documentation or example atleast. I appreciate if you could help me out.

**Comment by jeremyVignelles** [comment] 2017-09-28 06:06
I'm sorry for the confusion, but there is currently no Playlist feature (that's the point of #193).
So unfortunately you will have to wait until someone implements it (might be me in 1-2 weeks, but not sure if I will have time until that). Or maybe you can implement it and make a PR?

Closing as duplicate of #193

**Closed by jeremyVignelles** 2017-09-28 06:06 UTC
Labels: question
