### ISSUE TITLE
When video plaint, ContextMenuStrip not work.

### ISSUE THREAD

**Issue by aap4ixx** [ZeBobo5/Vlc.DotNet#421] opened 2018-05-16 14:31 UTC
I have a question.
When video not play (VLCControl have black font) ContextMenuStrip working OK.
But when start play video (RTSP stream) ContextMenuStrip stop working.
Ho i can call ContextMenuStrip when video plaing?

# Generic information
- **Vlc.DotNet version** : (2.2.5)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (2.2.8) (x86) + how did you get it?
Take from official side.
- **.net version** : (4.5)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU)
- **Operating system** : (Windows 10) (x64)

**Comment by jeremyVignelles** [comment] 2018-05-16 14:35
Probable duplicate of #107 . Please reopen if you mean something else.

**Closed by jeremyVignelles** 2018-05-16 14:35 UTC
