### ISSUE TITLE
Playing from folder

### ISSUE THREAD

**Issue by rubenje** [ZeBobo5/Vlc.DotNet#148] opened 2016-03-08 11:23 UTC
Hi,

I tried for several days to play a music directory. Is it possible to create and read a PlayList?
I tried to use setMedia, Play (uri)..., but the result is the same, no play music.

Thanks.
Ruben #

**Comment by storbild** [comment] 2017-09-22 11:32
Same problem here. Seems dotnet.forms only can play single files and dotnet.core can play playlists.
I would like to use playlists in winforms. Any suggestions for a workaround?

**Comment by jeremyVignelles** [comment] 2017-09-22 12:35
If Vlc.DotNet.Core can do that, it shouldn't be hard to port it to Vlc.DotNet.Forms. If you really need that feature, please make a pull request, or wait for someone else to do that (if ever someone does)

**Comment by jeremyVignelles** [comment] 2017-09-22 12:37
Possible duplicate of #193

**Comment by jeremyVignelles** [comment] 2019-07-15 20:38
Closing in favor of #193

**Closed by jeremyVignelles** 2019-07-15 20:38 UTC
