### ISSUE TITLE
Disposing Vlc object hangs Application

### ISSUE THREAD

**Issue by Tabrez-Khan** [ZeBobo5/Vlc.DotNet#237] opened 2017-03-27 14:09 UTC
From more than one week i am scratching my head as vlc object doesn't dispose even after Unregistering all Events and calling its Dispose() method.
Note: I am using WindowsFormHost to Host Vlc object in a WPF Application.
what i tried so far:
1) Adding this.Dispose method in Another Task with Thread.Sleep of 100 ms.
2) calling this.pause before disposing
and more.
But none of this worked for me.
Can you please solve this issue or atleast provide me a workaround with it.
ill be so thankful to you.

**Comment by jeremyVignelles** [comment] 2017-09-17 11:17
Could you try with latest version from NuGet and provide more info like:
- The version of libvlc you are using
- A sample code to reproduce (at what time do you call Dispose? Is it on the same thread that created libvlc?)

**Comment by Tabrez-Khan** [comment] 2017-12-07 09:27
Hi jeremy i asked the same question on stackoverflow you can find the link below:
[here](https://stackoverflow.com/questions/42687402/how-to-dispose-vlccontrol-for-wpf)

i dont know about LibVlc but

Vlc.DotNet.Forms version: 2014.10.15.0

**Comment by jeremyVignelles** [comment] 2017-12-26 10:15
Closing this since an answer has been provided on stackoverflow. Feel free to reopen if needed.

**Closed by jeremyVignelles** 2017-12-26 10:15 UTC
