### ISSUE TITLE
Why this controk will have an order window?

### ISSUE THREAD

**Issue by jeffreychen567** [ZeBobo5/Vlc.DotNet#287] opened 2017-08-11 07:24 UTC
I don't want to see this, order window.What should I do?

**Comment by jeremyVignelles** [comment] 2017-08-12 10:48
What do you call an "order window"? I don't understand your question.

**Comment by jeffreychen567** [comment] 2017-08-12 10:50
when my  program start,a command window jump up，like cmd command .i donnt want it

**Comment by jeremyVignelles** [comment] 2017-08-12 10:58
Duplicate of #248 and #267

**Closed** 2017-09-12 09:54 UTC
