### ISSUE TITLE
program crashes with more than 6 instances

### ISSUE THREAD

**Issue by xpachin** [ZeBobo5/Vlc.DotNet#274] opened 2017-07-19 14:52 UTC
does anyone knw how to have 20+ instances of form/wpf instances got working at the same time?
when i got 6-10 the program crashes (svhost stop working) without any message, so i presume is the memory access violation issue.
thanks!

**Comment by salihkaragoz** [comment] 2017-07-20 05:32
I didn't try over than 4 different cameras. But if it really It is a very big problem. Which version do you use in libraries?

**Comment by xpachin** [comment] 2017-07-20 16:24
the ones on the nuget packages

**Comment by jeremyVignelles** [comment] 2017-08-04 20:29
Did you look at the system memory usage after launching that much streams? I think this issue could be caused by the computer, not able to decode that many streams rather than a Vlc.DotNet issue.
Did you try launching 20+ Vlcs playing on your computer at a time?

**Comment by xpachin** [comment] 2017-08-08 20:20
nah the computer has 16GB of memory, the app usesbetween 4 to 8 GB... it looks more a memory leak or fragmentation problem

**Comment by jeremyVignelles** [comment] 2017-08-08 20:23
Yeah, but it might be a video memory issue or something like that. Does VLC show the same issue?

**Comment by salihkaragoz** [comment] 2017-08-10 12:46
@xpachin , The problem is about CPU.

**Comment by yewnok** [comment] 2018-02-13 13:32
I've already using 8 different instances at the same time without problems. It consumes about 45% of the CPU of my laptop.

**Comment by jeremyVignelles** [comment] 2018-02-13 13:50
I'm closing this since there was no answer from original poster. Please try with libvlc 3.0 and reopen if this is still an issue.

**Closed by jeremyVignelles** 2018-02-13 13:50 UTC
