### ISSUE TITLE
How to realize the real full screen with WinForm's VLC

### ISSUE THREAD

**Issue by wutangyuan** [ZeBobo5/Vlc.DotNet#646] opened 2020-05-21 07:57 UTC
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : (3.0.0)
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (3.0.7) (x64) + nuget
- **.net version** : (net472)
- **Project language** : (C#)
- **Project build architecture** : (AnyCPU (prefer 32bits))
- **Operating system** : (Windows 10 Home) (x64)

# Summary
How to realize the full screen with WinForm's VLC? I try to set  "VlcProvider.Video.AspectRatio" and "VlcProvider.Video.FullScreen", But the effect is not good. 

![1590047514(1)](https://user-images.githubusercontent.com/50666934/82536595-48082f00-9b7b-11ea-9cdb-f70772852c13.jpg)

(What happens, when, how? Steps to reproduce (with sample codes))

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment] 2020-05-21 08:30
Closing as a duplicate of #44 : Put your parent control in fullscreen instead of trying to use the libvlc function.

**Closed by jeremyVignelles** 2020-05-21 08:30 UTC
