### ISSUE TITLE
Freeze when try to seek rtmp stream

### ISSUE THREAD

**Issue by aykuter** [ZeBobo5/Vlc.DotNet#385] opened 2018-03-02 23:29 UTC
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : x64 + with vlc install
- **.net version** : 4.6.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : (Windows 8.1) (x64)

# Summary

I'm trying to stream rtmp from my server with vlc here my code : 

```
            DirectoryInfo di = new DirectoryInfo(@"C:\Program Files (x86)\VideoLAN\VLC");

            vlcControl1.VlcLibDirectory = di;

            vlcControl1.SetMedia(@"rtmp://serverip/vod/mp4:file/testfile.mp4");

         

            vlcControl1.Play();
```

But when i try to seek it's freeze. 

`vlcControl1.Time = Convert.ToInt32(textBox1.Text) * 60 * 1000;`

I can't seek it from vlc player too. But i don't have any idea why. I can seek my stream from mpc-hc without any problem. What should i do ? Is this problem related with vlc ? As i told you i can seek my stream perfectly with mpc-hc. Thanks for the help!

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment] 2018-03-03 09:50
If VLC has the same issue, you're posting on the wrong site.
You can try to install VLC 3.0.1 and see if the issue is fixed. If not, please report an issue on VLC's trac and wait for an answer there.

Oh, wait, you said rtmp? isn't it live streaming ? if it is, how can you seek in a live stream without recording/buffering first?

Closing this as it is not a Vlc.DotNet issue

**Closed by jeremyVignelles** 2018-03-03 09:50 UTC
