### ISSUE TITLE
VlcManager AccessViolation when application is stopping

### ISSUE THREAD

**Issue by Dimigergo** [ZeBobo5/Vlc.DotNet#546] opened 2019-05-22 08:04 UTC
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : Core
- **libvlc version** : 3.0.6 - x86  + VideoLAN.LibVLC.Windows nuget package
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 x64

# Summary
I have the following class to record or re-stream a source stream. These class instances are initialized and record 2-3 stream at the same time. When a trigger is hit the recording stops and the instance disposes. When I use the VlcMediaPlayer class without VlcManager the Accessviolation exception is shown when the second instance is disposed. Thats why I rewrite the code with the VlcManager and lower level architecture. Everithing is works fine, multiple records, multiple stop and disposes. but when I close my Windows service application, AccessViolation exception is shown. The `ReleaseVlcManager` static method is called when the service is disposing, but when I removed is the Exception is the same. This exception is thrown after my last line of the service stop if I have a breakpoint.

BTW is there any documentation of how to use reworked (3.0.0) VlcManager in proper way?

![accessviolation](https://user-images.githubusercontent.com/11498949/58157350-655ca180-7c78-11e9-96cf-e0a45e62ddc8.jpg)

`namespace MLR.MoLaRi.HQ.VRService.MM.VLC`
`{`
`    public class CVLCBase : MLR.Components.MessageProvider.CMessageProvider, IDisposable`
`    {`
`       #region Constants`

        private const int cStopResetEventTimeout = 60 * 1000;

        #endregion  

        #region Events

        public event EventHandler<Args.CIdArgs> OnVLCPlayerStopped;
        public event EventHandler<Args.CIdArgs> OnVLCPlayerStarted;

        #endregion

        #region Private Static Members

        private static VlcManager sVlcManager;

        #endregion

        #region Private Members

        private ManualResetEvent _stopResetEvent;
        private VlcMediaPlayerInstance _vlcMediaPlayerInstance;
        private VlcMediaInstance _vlcMediaInstance;
        private VlcMediaPlayerEventManagerInstance _vlcMediaPlayerEventManagerInstance;
        private EventCallback _mediaPlayerStoppedEventCallback;
        private EventCallback _mediaPlayerPlayingEventCallback;
        private string[] _mediaOptions;

        #endregion

        #region Private Methods

        private void OnVLCMediaPlayerLogHandler(IntPtr data, VlcLogLevel level, IntPtr logContext, string format, IntPtr args)
        {
            var byteLength = Components.CWin32Interops._vscprintf(format, args) + 1;
            var utf8Buffer = Marshal.AllocHGlobal(byteLength);

            string formattedDecodedMessage = null;
            try
            {
                Components.CWin32Interops.vsprintf(utf8Buffer, format, args);
                formattedDecodedMessage = Utf8InteropStringConverter.Utf8InteropToString(utf8Buffer);
            }
            finally
            {
                Marshal.FreeHGlobal(utf8Buffer);
            }

            sVlcManager.GetLogContext(logContext, out string module, out string file, out uint? line);

            if (formattedDecodedMessage != null)
            {
                switch (level)
                {
                    case VlcLogLevel.Debug:
                        this.Info(this, module + " - " + formattedDecodedMessage + " - " + this.ToString());
                        break;
                    case VlcLogLevel.Notice:
                        this.Info(this, module + " - " + formattedDecodedMessage + " - " + this.ToString());
                        break;
                    case VlcLogLevel.Warning:
                        this.Warning(this, module + " - " + formattedDecodedMessage + " - " + this.ToString());
                        break;
                    case VlcLogLevel.Error:
                        this.Error(this, module + " - " + formattedDecodedMessage + " - " + this.ToString());
                        break;
                }
            }
            else
                this.Error(this, module + " - Formatted message parsing error! - " + this.ToString());
        }

        #endregion

        #region Public Properties

        public SharedTypes.CVideoId VideoId { get; private set; }
        public Uri SourceUri { get; private set; }        

        #endregion

        #region Constructor

        public CVLCBase(SharedTypes.CVideoId videoId, Uri sourceUri, string[] mediaOptions)
        {
            MLR.Components.MessageProvider.CMessageProvider.Add(this);

            this._mediaOptions = mediaOptions;

            this.VideoId = videoId;
            this.SourceUri = sourceUri;

            DirectoryInfo vlcLibDirectory = new DirectoryInfo(
                Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory,
                    "libvlc",
                    IntPtr.Size == 4 ? "win-x86" : "win-x64"));

            this._stopResetEvent = new ManualResetEvent(false);

            if (sVlcManager == null)
                sVlcManager = new VlcManager(vlcLibDirectory, null);

            this._vlcMediaInstance = sVlcManager.CreateNewMediaFromLocation(this.SourceUri.ToString());
            this._vlcMediaInstance.AddOptionToMedia(sVlcManager, this._mediaOptions);
            this._vlcMediaPlayerInstance = sVlcManager.CreateMediaPlayerFromMedia(this._vlcMediaInstance);
            this._vlcMediaPlayerEventManagerInstance = sVlcManager.GetMediaPlayerEventManager(this._vlcMediaPlayerInstance);

            this._mediaPlayerStoppedEventCallback = new EventCallback(this.OnVLCMediaPlayerStopped);
            this._mediaPlayerPlayingEventCallback = new EventCallback(this.OnVLCMediaPlayerPlaying);

            sVlcManager.AttachEvent(
                this._vlcMediaPlayerEventManagerInstance,
                EventTypes.MediaPlayerStopped,
                this._mediaPlayerStoppedEventCallback);

            sVlcManager.AttachEvent(
                this._vlcMediaPlayerEventManagerInstance,
                EventTypes.MediaPlayerPlaying,
                this._mediaPlayerPlayingEventCallback);

            sVlcManager.SetLog(new LogCallback(this.OnVLCMediaPlayerLogHandler));
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                MediaStates state = sVlcManager.GetMediaPlayerState(this._vlcMediaPlayerInstance);
                this.Info("Disposing VLCMediaPlayer (state: " + state.ToString() + "): " + this.ToString());

                if (state != MediaStates.Stopped)
                    this.StopPlayer(null);

                this.Info("Disposing continue: " + this.ToString());

                sVlcManager.DetachEvent(this._vlcMediaPlayerEventManagerInstance,
                    EventTypes.MediaPlayerStopped,
                    this._mediaPlayerStoppedEventCallback);

                sVlcManager.DetachEvent(this._vlcMediaPlayerEventManagerInstance,
                    EventTypes.MediaPlayerPlaying,
                    this._mediaPlayerPlayingEventCallback);
               
                this._vlcMediaPlayerEventManagerInstance?.Dispose();

                this._mediaPlayerStoppedEventCallback = null;
                this._mediaPlayerPlayingEventCallback = null;

                sVlcManager.ReleaseMediaPlayer(this._vlcMediaPlayerInstance);
                sVlcManager.ReleaseMedia(this._vlcMediaInstance);

                this._stopResetEvent?.Dispose();

                this.Info("Disposed ready: " + this.ToString());
            }

            MLR.Components.MessageProvider.CMessageProvider.Remove(this);
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }

        #endregion

        #region Protected Methods        

        protected virtual void OnVLCMediaPlayerStopped(IntPtr args)
        {
            this.Info(CFL.Entry(out CFL fL, "VLC media player is stopped. VLCPlayer: " + this.ToString()));

            this.OnVLCPlayerStopped?.Invoke(this, new Args.CIdArgs(fL, this.VideoId));

            this.Info(CFL.Log(fL, "VLC media player stopped event is raised. VLCPlayer: " + this.ToString()));

            this._stopResetEvent.Set();
        }

        protected virtual void OnVLCMediaPlayerPlaying(IntPtr args)
        {
            this.Info(CFL.Entry(out CFL fL, "VLC media player is started. VLCPlayer: " + this.ToString()));

            this.OnVLCPlayerStarted?.Invoke(this, new Args.CIdArgs(fL, this.VideoId));
        }

        #endregion

        #region Public Methods        

        public void StartPlayer(CFL fL)
        {
            try
            {
                sVlcManager.Play(this._vlcMediaPlayerInstance);
            }
            catch (Exception ex)
            {
                this.Error(ex, CFL.Log(fL, this.ToString()));
            }
        }

        public void StopPlayer(CFL fL)
        {
            if (this._vlcMediaPlayerInstance != null)
            {
                try
                {
                    MediaStates state = sVlcManager.GetMediaPlayerState(this._vlcMediaPlayerInstance);
                    this.Info(CFL.Log(fL, "Stopping VLC media player. Current state: " + state.ToString() + " VLCPlayer: " + this.ToString()));

                    if (state != MediaStates.Stopped)
                    {
                        this._stopResetEvent.Reset();

                        sVlcManager.Stop(this._vlcMediaPlayerInstance);
                        if (!this._stopResetEvent.WaitOne(cStopResetEventTimeout))
                            this.Warning(CFL.Log(fL, "Stop reset event timaout. VLCPlayer: " + this.ToString()));
                    }
                }
                catch (Exception ex)
                {
                    this.Error(ex, CFL.Log(fL, this.ToString()));
                }
            }
            else
                this.Error(CFL.Log(fL, "VLC media player is not initialized. VLCPlayer: " + this.ToString()));
        }

        public override string ToString()
        {
            return "VideoId: " + this.VideoId.ToString()
                + " SourceUri: " + this.SourceUri.ToString();
        }

        #endregion

        #region Public Static Methods

        public static void ReleaseVlcManager()
        {
            sVlcManager?.Dispose();
        }

        #endregion
    }
}

- [X] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment] 2019-05-22 09:56
You shouldn't use the VlcManager directly, it's pretty low level. Use the VlcMediaPlayer instead, and, if you really need lower level acces, please use `MediaPlayer.Manager`

> When a trigger is hit the recording stops and the instance disposes. 
What kind of trigger is that? User action? VLC event trigger?

Can you try to remove the log callback for now, just to be sure that it's not the cause of your access violations?

**Comment by Dimigergo** [comment] 2019-05-22 11:00
Trigger is a 3rd party camera action, but the instance disposing works perfectly. Only the application exiting is wrong when manually stop the Windows service.

I use the VlcManager directly because this issue: #482.

When I switch off the log (commented this line: 
`sVlcManager.SetLog(new LogCallback(this.OnVLCMediaPlayerLogHandler));)`
the problem is still alive.

Thanks!

**Comment by Dimigergo** [comment] 2019-05-22 11:19
When I use this code the problem is that the second instance stop raised AccessViolationException.
The same exception occures if I comment the log eventhandler attach:
`this._vlcMediaPlayer.Log += this.OnVLCMediaPlayerLogHandler;`

![accessviolation2](https://user-images.githubusercontent.com/11498949/58170497-d78eaf80-7c93-11e9-8f08-f6a257943077.jpg)

Thats why I use VlcManager directly.

`namespace MLR.MoLaRi.HQ.VRService.MM.VLC`
`{`
`    public class CVLCBase : MLR.Components.MessageProvider.CMessageProvider, IDisposable`
`    {`
`        #region Constants `

        private const int cStopResetEventTimeout = 60 * 1000;

        #endregion  

        #region Events

        public event EventHandler<Args.CIdArgs> OnVLCPlayerStopped;
        public event EventHandler<Args.CIdArgs> OnVLCPlayerStarted;

        #endregion

        #region Private Members

        private ManualResetEvent _stopResetEvent;
        private VlcMediaPlayer _vlcMediaPlayer;
        private string[] _mediaOptions;

        #endregion

        #region Private Methods

        private void OnVLCMediaPlayerLogHandler(object sender, VlcMediaPlayerLogEventArgs e)
        {
            switch (e.Level)
            {
                case Vlc.DotNet.Core.Interops.Signatures.VlcLogLevel.Debug:
                    this.Info(this, e.Module + " - " + e.Message);
                    break;
                case Vlc.DotNet.Core.Interops.Signatures.VlcLogLevel.Notice:
                    this.Info(this, e.Module + " - " + e.Message);
                    break;
                case Vlc.DotNet.Core.Interops.Signatures.VlcLogLevel.Warning:
                    this.Warning(this, e.Module + " - " + e.Message);
                    break;
                case Vlc.DotNet.Core.Interops.Signatures.VlcLogLevel.Error:
                    this.Error(this, e.Module + " - " + e.Message);
                    break;
            }
        }

        #endregion

        #region Public Properties

        public SharedTypes.CVideoId VideoId { get; private set; }
        public Uri SourceUri { get; private set; }        

        #endregion

        #region Constructor

        public CVLCBase(SharedTypes.CVideoId videoId, Uri sourceUri, string[] mediaOptions)
        {
            MLR.Components.MessageProvider.CMessageProvider.Add(this);

            this._mediaOptions = mediaOptions;

            this.VideoId = videoId;
            this.SourceUri = sourceUri;

            DirectoryInfo vlcLibDirectory = new DirectoryInfo(
                Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory,
                    "libvlc",
                    IntPtr.Size == 4 ? "win-x86" : "win-x64"));

            this._stopResetEvent = new ManualResetEvent(false);

            this._vlcMediaPlayer = new VlcMediaPlayer(vlcLibDirectory);
            this._vlcMediaPlayer.Log += this.OnVLCMediaPlayerLogHandler;
            this._vlcMediaPlayer.Stopped += this.OnVLCMediaPlayerStopped;
            this._vlcMediaPlayer.Playing += this.OnVLCMediaPlayerPlaying;
            this._vlcMediaPlayer.SetMedia(sourceUri, mediaOptions);
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.Info("Disposing VLCMediaPlayer (state: " + this._vlcMediaPlayer.State.ToString() + "): " + this.ToString());

                if (this._vlcMediaPlayer.State != MediaStates.Stopped)
                    this.StopPlayer(null);

                this.Info("Disposing continue: " + this.ToString());

                this._vlcMediaPlayer.Log -= this.OnVLCMediaPlayerLogHandler;
                this._vlcMediaPlayer.Stopped -= this.OnVLCMediaPlayerStopped;
                this._vlcMediaPlayer.Playing -= this.OnVLCMediaPlayerPlaying;
                this._vlcMediaPlayer.Dispose();

                this._stopResetEvent?.Dispose();

                this.Info("Disposed ready: " + this.ToString());
            }

            MLR.Components.MessageProvider.CMessageProvider.Remove(this);
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }

        #endregion

        #region Protected Methods        

        protected virtual void OnVLCMediaPlayerStopped(object sender, VlcMediaPlayerStoppedEventArgs args)
        {
            this.Info(CFL.Entry(out CFL fL, "VLC media player is stopped. VLCPlayer: " + this.ToString()));

            this.OnVLCPlayerStopped?.Invoke(this, new Args.CIdArgs(fL, this.VideoId));

            this.Info(CFL.Log(fL, "VLC media player stopped event is raised. VLCPlayer: " + this.ToString()));

            this._stopResetEvent.Set();
        }

        protected virtual void OnVLCMediaPlayerPlaying(object sender, VlcMediaPlayerPlayingEventArgs args)
        {
            this.Info(CFL.Entry(out CFL fL, "VLC media player is started. VLCPlayer: " + this.ToString()));

            this.OnVLCPlayerStarted?.Invoke(this, new Args.CIdArgs(fL, this.VideoId));
        }

        #endregion

        #region Public Methods        

        public void StartPlayer(CFL fL)
        {
            try
            {
                this._vlcMediaPlayer.Play();
            }
            catch (Exception ex)
            {
                this.Error(ex, CFL.Log(fL, this.ToString()));
            }
        }

        public void StopPlayer(CFL fL)
        {
            if (this._vlcMediaPlayer != null)
            {
                try
                {
                    this.Info(CFL.Log(fL, "Stopping VLC media player. Current state: " + this._vlcMediaPlayer.State.ToString() + " VLCPlayer: " + this.ToString()));

                    if (this._vlcMediaPlayer.State != MediaStates.Stopped)
                    {
                        this._stopResetEvent.Reset();

                        this._vlcMediaPlayer.Stop();
                        if (!this._stopResetEvent.WaitOne(cStopResetEventTimeout))
                            this.Warning(CFL.Log(fL, "Stop reset event timaout. VLCPlayer: " + this.ToString()));
                    }
                }
                catch (Exception ex)
                {
                    this.Error(ex, CFL.Log(fL, this.ToString()));
                }
            }
            else
                this.Error(CFL.Log(fL, "VLC media player is not initialized. VLCPlayer: " + this.ToString()));
        }

        public override string ToString()
        {
            return "VideoId: " + this.VideoId.ToString()
                + " SourceUri: " + this.SourceUri.ToString();
        }

        #endregion
    }
}

**Comment by jeremyVignelles** [comment] 2019-05-22 12:06
> I use the VlcManager directly because this issue: #482.
I don't see how this is related. #482 has been fixed and merged into master since then. If you have an AccessViolationException, this is totally unrelated.

You should not try to use VlcManager directly, you're trying to reimplement what the VlcPlayer does.
Please make a Minimal, Reproductible example an push it in a github repository so that I can actually run the code and see what's wrong. See https://stackoverflow.com/help/reprex for how to do that.

**Comment by Dimigergo** [comment] 2019-05-23 07:58
I made a small console app for reproduce the issue.

[AccessViolationConsoleApp.zip](https://github.com/ZeBobo5/Vlc.DotNet/files/3210893/AccessViolationConsoleApp.zip)

When app is started wait for 5-6 seconds and press enter, the exception will occure on the second streamer Stop() function. No matter if the stream is alive, or can not connect to it.

Thanks!

**Comment by jeremyVignelles** [comment] 2019-05-23 08:08
Thanks for your project.

Do you know if that condition is true in the Dispose, when it crashes ?
```
if (this._vlcMediaPlayer.State != MediaStates.Stopped)
```

You don't need to Stop() if you Dispose() the media player : https://github.com/ZeBobo5/Vlc.DotNet/blob/b9df299376cc418a3f68157d4b43433413e465de/src/Vlc.DotNet.Core/VlcMediaPlayer/VlcMediaPlayer.cs#L91

Can you also try to wait a little between these line in Program.cs, or remove the first line?

```
                        vlcLieStream2.StopPlayer();
                        vlcLieStream2.Dispose();
```

With all that, under which cases does it crash?

I'll try to have a look soon, but I can't promise anything. Please ping me if not done by the end of the week.

**Comment by Dimigergo** [comment] 2019-05-23 08:17
When I commented this line:

When I remove StopPlayer from everywhere the error occures in Dispose().

                //if (this._vlcMediaPlayer.State != MediaStates.Stopped)
                //    this.StopPlayer();


                Task.Run(() =>
                {
                    try
                    {
                        vlcLieStream1.Dispose();
                        vlcLieStream2.Dispose();

                        Console.WriteLine("Disposed.");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.Message);
                    }
                });

![accessviolation3](https://user-images.githubusercontent.com/11498949/58236713-c69d7700-7d43-11e9-89d3-f1af99024c23.jpg)

**Comment by Dimigergo** [comment] 2019-05-27 08:07
Ping @jeremyVignelles

:)

**Comment by jeremyVignelles** [comment] 2019-05-27 19:56
I reproduced the issue. I'm trying stuffs and keep you posted.

Side note: In libVLC 3.0, MediaPlayer.Stop() is synchronous. That is, you don't have to use your ManualResetEvent, because your OnVLCMediaPlayerStopped is called before Stop() returns.

This will likely change in libvlc 4.0

**Comment by jeremyVignelles** [comment] 2019-05-27 21:49
After testing, I've come down to this code that shows the issue:

```cs
using System;
using System.IO;
using Vlc.DotNet.Core;

namespace ConsoleApp1
{
    class Program
    {
        private static readonly string source = "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov";

        static void Main(string[] args)
        {

            DirectoryInfo vlcLibDirectory = new DirectoryInfo(
                Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory,
                    "libvlc",
                    IntPtr.Size == 4 ? "win-x86" : "win-x64"));

            var vlcLieStream1 = new VlcMediaPlayer(vlcLibDirectory);
            vlcLieStream1.Play(source, new[]
            {
                ":sout=#rtp{sdp=rtsp://127.0.0.1:5554/1}"
            });

            var vlcLieStream2 = new VlcMediaPlayer(vlcLibDirectory);
            vlcLieStream2.Play(source, new[]
            {
                ":sout=#rtp{sdp=rtsp://127.0.0.1:5554/2}"
            });

            Console.WriteLine("Press ENTER to dispose");
            Console.ReadLine();

            vlcLieStream1.Dispose();
            vlcLieStream2.Dispose();

            Console.WriteLine("Press ENTER to quit");
            Console.ReadLine();
        }
    }
}
```

If I change the second `sout` port to 5555, the crash is gone. What's weird is that I can't reproduce with C code...

**Comment by jeremyVignelles** [comment] 2019-05-27 22:35
So, I've got a good news and a bad news.

The good news is that I managed to reproduce the bug in C, you can find that here : 
https://github.com/jeremyVignelles/TestLibvlcNative/commit/30dfef784a90a174a2c530fa97c21dbbff59ffd5

It makes more sense to me, because it is crashing only when using a specific parameter combination, and Vlc.DotNet doesn't interpret those parameters.

The bad news is that the issue lies in the VLC plugins itself, so that will be hard to track down and fix (and even more if that only happens on windows).

From now, you have a few options:
- Report the bug on https://trac.videolan.org, which I encourage you to do anyway (maybe someone will have the same issue or wants to fix that in the future). You can link the commit mentioned above for the reproducing bug, and this issue for reference.
- Find a workaround, like the one I suggested : stream on different ports. You can also change the order of Disposal. This code works:
```cs
            vlcLieStream1.Stop();
            vlcLieStream2.Stop();
            vlcLieStream1.Dispose();
            vlcLieStream2.Dispose();
```

Good luck 🙂 
Don't hesitate if you need something else.

**Closed by jeremyVignelles** 2019-05-27 22:35 UTC

**Comment by Dimigergo** [comment] 2019-05-28 07:19
Thank you very much @jeremyVignelles!
