### ISSUE TITLE
Faulting module name: libvlccore.dll, version: 2.2.2.0, time stamp: 0x00000000

### ISSUE THREAD

**Issue by SkinnySackboy** [ZeBobo5/Vlc.DotNet#597] opened 2019-11-15 11:20 UTC
Hi,

This is one of those "I'm not really sure what's going on" issues I'm afraid. We've got a WPF application using the WinForms VLC control (for performance reasons). I don't think this has anything to do with the issue but I just thought I'd mention it.

Our users (who use this library to view various streams) sometimes experience unmanaged exceptions which cause our application to crash - which I'm unable to capture at all, so the application just dies.

The Event Viewer always says the same thing:
Faulting module name: libvlccore.dll, version: 2.2.2.0, time stamp: 0x00000000
Faulting module path: C:\Program Files\VideoLAN\VLC\libvlccore.dll
Faulting application path: myapplication.exe

Uninstalling/reinstalling VLC does not seem to help, as does changing versions. When the same streams are streamed to VLC directly, VLC does seem to momentarily pause the stream, go blank and subsequently resume - whereas VLC.DotNet causes an unmanaged exception to be thrown.

I'm pretty sure this is related to something on the stream itself, but of course being non-deterministic it is nigh on impossible for me to reproduce - it just randomly happens sometimes to some users.

Is anyone able to shed any light on this please?

Thanks in advance.

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WinForms hosted inside WPF (.NET Framework)
- **libvlc version** : x64 - installed by downloading it from videolan.org 
- **.net version** : 4.7.2
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows 10 x64 (occurs also on Windows 7 x64)

**Comment by jeremyVignelles** [comment] 2019-11-15 11:58
This is a native crash caused by vlc itself. I'm afraid I can't do much about it.
Vlc 2.2 is not supported anymore, and isn't supposed to work with Vlc.DotNet 3.
Next time, please fill the issue template, in particular, you didn't say which Vlc.DotNet version you are using.

**Comment by SkinnySackboy** [comment] 2019-11-15 13:15
My apologies @jeremyVignelles, I've edited the original post to contain the information form the template.

Thanks for the heads up about not mixing Vlc.DotNet versions with other VLC versions, I was not aware of this. Presumably 3.x.x should be used with any corresponding v3 version of VLC?

**Comment by jeremyVignelles** [comment] 2019-11-15 14:31
> Presumably 3.x.x should be used with any corresponding v3 version of VLC?
Indeed. It should work because APIs didn't change much between 2.x and 3.x (only a few additions and some deprecated methods). However, libvlc 4 will be totally incompatible with libvlc 3.

I will close this issue as I can't really help with that. Try to narrow down the issue to a specific version of vlc, see if you can reproduce with a specific stream or with VLC itself. See if VLC4 has the same issue...

**Closed by jeremyVignelles** 2019-11-15 14:31 UTC

**Comment by SkinnySackboy** [comment] 2019-11-18 08:20
Ok thanks.

In general, what's the best way of knowing which version of Vlc.DotNet is compatible with which version of VLC?

**Comment by mfkl** [comment] 2019-11-18 08:29
Vlc.DotNet 2.x versions work with vlc 2.x versions only.

Vlc.DotNet 3.x versions work with vlc 3.x versions only.

AFAIK.

**Comment by jeremyVignelles** [comment] 2019-11-18 08:29
The rule is now:
For a given Vlc.DotNet version `a.b.c`, you may use the libvlc versions `a.*` (same major version)
An increment in `b` can introduce breaking changes, and an increment in `c` may add new features and fix bugs.

As far as I know, the rule is the same in LibVLCSharp.

**Comment by mfkl** [comment] 2019-11-18 08:33
> libvlc version : x64 - installed by downloading it from videolan.org

The better way is to use nuget: https://www.nuget.org/packages/VideoLAN.LibVLC.Windows

Because if your client updates/downgrades VLC on its local machine, and your app depends on it, your app will likely break.

**Comment by SkinnySackboy** [comment] 2019-11-18 09:21
Thanks everyone.
