### ISSUE TITLE
Kernel32 Error On Media Player Initialisation 

### ISSUE THREAD

**Issue by ejdigby** [ZeBobo5/Vlc.DotNet#350] opened 2017-11-13 20:55 UTC
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.1
- **Vlc.DotNet project used** : Core
- **libvlc version** : 2.2.6 (x86) from VLC website
- **.net version** : Mono 5.4.1.6 Runtime / dotnet 4.6.1
- **Project language** : C#
- **Project build architecture** : x86
- **Operating system** : macOS High Sierra

# Summary

I followed the wiki getting started guide and on creating a new mediaPlayer a ```System.DllNotFoundException``` is thrown with a ```kernel32``` description. 

The ```libDirectory``` is correct and the libvlc dll files are in the folder. Any Ideas?

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment] 2017-11-13 21:01
Hi,
unfortunately, Vlc.DotNet does not support other platforms than Windows yet.
I am trying to implement linux as well (see a branch on my fork) but I'm still facing issues that will make it hard to implement at the time being.
However, feel free to help if you want to, and tell us on gitter.

I'm going to close this for now, because it's not a bug, it's just the way it's implemented( you can load .net DLL on MacOS, but not native windows DLL)

**Closed by jeremyVignelles** 2017-11-13 21:01 UTC
