### ISSUE TITLE
Exception on VlcControl Dispose

### ISSUE THREAD

**Issue by ae72rus** [ZeBobo5/Vlc.DotNet#497] opened 2018-12-10 18:42 UTC
Hi, i have this issue randomly:
### Generic information

- **Vlc.DotNet version**: 3.0.0-develop296
- **Vlc.DotNet project used**: Core
- **libvlc version**: VideoLAN.LibVLC.Windows (version 3.0.3), machine runs on x64
- **.net version**: 4.6.1
- **Project language**: C#
- **Project build architecture**: x64
- **Operating system**: Windows 10 x64

### Summary
In case with multiple players sometimes Dispose() will throw System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'

**Scenario to reproduce issue:**
Create more than one instance of VlcMediaPlayer. SetMedia and Play for each of they
Start disposing instances.
**Result:** sometimes System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.' was thrown.

**Stacktrace**

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) in f:\dd\ndp\clr\src\BCL\system\throwhelper.cs:line 99
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare() in f:\dd\ndp\clr\src\BCL\system\collections\generic\list.cs:line 1178
   at Vlc.DotNet.Core.VlcMediaPlayer.Dispose(Boolean disposing)
   at Vlc.DotNet.Wpf.VlcVideoSourceProvider.Dispose(Boolean disposing)
   at Vlc.DotNet.Wpf.VlcControl.Dispose()
   at CamSwitcher.UI.Controls.MediaPlayer.<>c__DisplayClass85_0.<Dispose>b__2() in V:\!GIT\NetworkDevicesMonitor\CamSwitcher\UI\Controls\MediaPlayer.cs:line 608
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 954
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 902
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 891
   at System.Threading.ThreadHelper.ThreadStart() in f:\dd\ndp\clr\src\BCL\system\threading\thread.cs:line 111

Is there any workarounds?

**Comment by jeremyVignelles** [comment] 2018-12-10 18:43
Please fill the issue template, otherwise I won't be able to help

**Comment by ae72rus** [comment] 2018-12-10 19:02
> Please fill the issue template, otherwise I won't be able to help

done!

**Comment by jeremyVignelles** [comment] 2018-12-10 19:22
Might be fixed by #490

**Comment by jeremyVignelles** [comment] 2019-07-15 20:10
Can you confirm that the issue is not present in the current release version of Vlc.DotNet ?
Feel free to reopen if the issue is still there.

**Closed by jeremyVignelles** 2019-07-15 20:10 UTC
