### ISSUE TITLE
Use this to connect to an instance of vlc that is running?

### ISSUE THREAD

**Issue by lzinga** [ZeBobo5/Vlc.DotNet#186] opened 2016-07-27 00:32 UTC
Can you use this to connect to an instance of vlc that is running?

So say I can open VLC and I can manipulate the VLC window using this library. I have looked through the libraries and can't seem to find anything.

**Comment by jeremyVignelles** [comment] 2017-09-13 21:57
closed as duplicate of #192

**Closed by jeremyVignelles** 2017-09-13 21:57 UTC
