### ISSUE TITLE
EMGU 4.1 nuget freezes the VLC player in the Window

### ISSUE THREAD

**Issue by wolfysan** [ZeBobo5/Vlc.DotNet#564] opened 2019-07-09 08:56 UTC
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.7.1
- **Vlc.DotNet project used** : WPF
- **libvlc version** : Visual Studio Nuget
- **.net version** : 4.5.1
- **Project language** : C#
- **Project build architecture** : AnyCPU (prefer 32bits)
- **Operating system** : Windows 10 x64

# Summary
I have a project that uses this Nuget Library. And it works. The problem appears when I instantiate EMGU (Emgu.cv 4.1.0.3420) VideoCapture class, that gets frames from an IP camera (different from the one VLC uses). The VLC player stops displaying frames.

Do the Nugets use some shared code by any chance? 

- [x] I confirm that my issue doesn't happen in VLC itself.

**Comment by mfkl** [comment] 2019-07-09 08:58
Share your code and logs please.

`(Emgu.cv 4.1.0.3420) VideoCapture class` -> I do not know what that is.

**Comment by wolfysan** [comment] 2019-07-09 09:04
EMGU is a C# library that wraps around OpenCV. I use it to handle frame grabbing from USB Cameras, IP cameras, video files, and so on.
I have no logs generated by the VLC. what options should I put to get them?

**Comment by jeremyVignelles** [comment] 2019-07-15 19:53
VLC shows logs in the standard output by default. Please see this documentation to know how to write them to a log file : https://github.com/ZeBobo5/Vlc.DotNet/wiki/Getting-started#how-to-debug

Vlc.DotNet itself is unlikely to cause this kind of conflicts I guess, but libvlc can probably cause that.
We don't have the needed throughput to understand your issue, learn EMGU, figure out how to reproduce your issue in a simple project and fix the bug.

I'm sure you can help by creating a simple project that includes both EMGU and Vlc.DotNet, load a video file (maybe through a public webserver) in EMGU and in Vlc.DotNet. We should be able to reproduce on our machine by "clone/build/run/boom".

Without this project, we can only make guesses, like this one : Maybe VLC is struggling to display the frames due to the high CPU load. Maybe it doesn't show anything due to a conflict, maybe in Direct3D11. We don't know.

Please make a project, fix it yourself, or wait for someone having the same issue fix that for you.

**Comment by jeremyVignelles** [comment] 2019-07-23 19:15
Did you manage to find a solution? Do you still need help?

**Comment by jeremyVignelles** [comment] 2019-08-03 09:29
Closing since you didn't answer. Please reopen with the requested info if you still need help.

**Closed by jeremyVignelles** 2019-08-03 09:29 UTC
