### ISSUE TITLE
'AccessViolationException' After Windows update to 1709

### ISSUE THREAD

**Issue by evo744** [ZeBobo5/Vlc.DotNet#334] opened 2017-10-19 14:57 UTC
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 2.2.0
- **Vlc.DotNet project used** : WinForms
- **libvlc version** : AnyCPU (nuget)
- **.net version** : 4.5
- **Project language** : VB.net
- **Project build architecture** : AnyCPU
- **Operating system** : Windows 10 Enterprise 64bit built 1709

# Summary
After the windows update to 1709 I get this error whenever I try to play anything:
`An unhandled exception of type 'System.AccessViolationException' occurred in mscorlib.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

Also if I try to use the last version I get (2.2.1 & 2.2.1-develop218): 
`An exception of type 'System.IO.FileLoadException' occurred in PrivateMediaPlayer.exe but was not handled in user code

Additional information: Could not load file or assembly 'Vlc.DotNet.Core.Interops, Version=2014.10.15.0, Culture=neutral, PublicKeyToken=84529da31f4eb963' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`
I have Visual Studio 2013 Ultimate Update 5 with up to date .net framework installed (4.7).

- [X] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment] 2017-10-19 15:47
You might be able to solve the issue of loading the assembly by trying the following:
- clean/rebuild your solution
- uninstall/reinstall Vlc.DotNet 2.2.1
- removing the packages folder in the solution
- the above line + cleaning the Nuget cache

For the access violation exception, it looks like something got broken in libvlc side, maybe some API that is not working anymore. which version of libvlc are you using? could you try to update to vlc -3.0.0 nightly build?

**Comment by evo744** [comment] 2017-10-19 15:58
I have tried the last nightly and a slightly earlier one with the same result

**Comment by jeremyVignelles** [comment] 2017-10-19 16:05
OK, feel free to come on gitter if you need some help.
Are you able to run a vlc 3.0.0 on your machine?

**Comment by jeremyVignelles** [comment] 2017-10-19 21:10
As discussed on gitter, the issue is not with Vlc.DotNet itself but with the client code (some race conditions as it seems). Closing this issue

**Closed by jeremyVignelles** 2017-10-19 21:10 UTC
