### ISSUE TITLE
I need to get frame from video file or rtsp. 

### ISSUE THREAD

**Issue by arnoldhoward** [ZeBobo5/Vlc.DotNet#532] opened 2019-03-07 09:54 UTC
I am a beginner of wpf, i am going to make the LPR project that process the frame from rtsp or video.
I already made the engine from image, but i stopped at get frame processing.
Can u send me the simple sample code that process the frame from rtsp or video ?
For example, convert the color frame to gray and display code.
I already look at the SetVideoCallbacks  function, but i can't know how should i use it.
Frame processing, is the main working for video processing, but there is no proper sample for this.
I really need ur helpness.
I will wait for ur reply.
Thanks.

**Comment by jeremyVignelles** [comment] 2019-03-07 10:34
Closing as duplicate of #522 and #507

**Closed by jeremyVignelles** 2019-03-07 10:34 UTC
