### ISSUE TITLE
takesnapshot is doesn't work

### ISSUE THREAD

**Issue by jeffreychen567** [ZeBobo5/Vlc.DotNet#280] opened 2017-08-04 08:01 UTC
vlcControl1.TakeSnapshot(@"d:\aa.jpg");

This doesn't work.why?

**Comment by jeremyVignelles** [comment] 2017-08-04 20:07
Please be more precise. Does it show any error message? Any crash?

**Comment by jeffreychen567** [comment] 2017-08-05 09:47
no err message，The file is not generated in the specified directory.

**Comment by jeffreychen567** [comment] 2017-08-05 09:48
Running normal.

**Comment by jeremyVignelles** [comment] 2017-09-17 10:41
Closing as I cannot reproduce. If this is still an issue, please reopen and provide a sample code and more details about what you are trying to do.

I tried reproducing by adding a Snapshot button to the WPF interface linked to this click handler:
```
        private void Snapshot_Click(object sender, RoutedEventArgs e)
        {
            myControl.MediaPlayer.TakeSnapshot(@"d:\aa.jpg");
        }
```

**Closed by jeremyVignelles** 2017-09-17 10:41 UTC
